apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d7ywk6jcr-go 
  janus-idp.io/tekton: d7ywk6jcr-go
  backstage.io/kubernetes-id: d7ywk6jcr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d7ywk6jcr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml